Make Inter font paths relative.
element-hq/element-web pull request #20040
Opened 2021-12-04 07:17 UTC by emikulic

Currently, paths look like /fonts/Inter which is fine if Element is installed in the wwwroot.
This change makes the paths relative (./fonts/Inter) which helps when it's not.

Credit goes to @rkfg.

Fixes #17575.

2021-12-06 07:42 UTC, gsouquet requested changes
Thank you for raising that concern. It appears that you're not the only one to face this issue as I can see some reverse proxy rules on some config that deal exactly with that.

I'm not convinced that this the approach I'd want us to take to fix this particular problem. Dabbling with the [`HtmlWebpackConfig`](https://github.com/jantimon/html-webpack-plugin) sounds a bit more maintanable and will convey the intent a bit better.

It appears that the `path` or `publicPath` option seems to achieve what you're after.
I'd also be curious to understand why this is an issue for this scenario and not for the JavaScript bundles

2021-12-07 02:20 UTC, emikulic commented
> curious to understand why this is an issue for this scenario and not for the JavaScript bundles

This = fonts?

Looking at DevTools, with Element 1.9.5 everything loads fine (so I guess via relative paths) except for these fonts.

2021-12-07 08:03 UTC, gsouquet commented
yes, this = fonts
I believe a more maintainable fix is to understand how to make webpack return relative paths rather than tweaking the `index.html` like it's  been suggested in this pull request

2021-12-08 00:09 UTC, emikulic commented
That's fair enough. I don't know how to do that.

2024-09-06 17:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/element-web?pullRequest=20040) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/element-web?pullRequest=20040) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/element-web?pullRequest=20040) it.</sub>

2024-09-08 03:29 UTC, emikulic commented
Apparently this got fixed: https://github.com/element-hq/element-web/issues/17575#issuecomment-1513221717

2024-09-08 03:29 UTC, closed without merging