Remove message audio element (for another pr)
element-hq/element-web pull request #25477
Opened 2023-05-30 10:54 UTC by SuperKenVery

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

Works with https://github.com/matrix-org/matrix-react-sdk/pull/10995

Signed-off-by: 许煜恒 xyhken@icloud.com

2023-05-31 00:35 UTC, SuperKenVery commented
Cannot pass test because

https://github.com/matrix-org/matrix-react-sdk/pull/10995#issuecomment-1569320311

2023-06-26 14:48 UTC, germain-gg requested changes
This sounds like the issue you're experiencing with Element appearing in media control will continue until you delete all the audio element and make things play through the WebAudio API.

2023-06-26 14:55 UTC, SuperKenVery commented
Hmm... seems true. Currently it works because sound other than message ringtone hasn't been played...

Will try to do that more thoroughly :D

2024-07-04 16:18 UTC, t3chguy approved these changes

2024-07-04 18:55 UTC, merged