sign images using cosign
element-hq/element-web pull request #26817
Opened 2024-01-03 09:43 UTC by gaelgatelement

2024-01-03 09:44 UTC, t3chguy requested changes
Please provide context, or an issue which provides context.

2024-01-03 09:48 UTC, gaelgatelement commented
> Please provide context, or an issue which provides context.

Context : https://github.com/element-hq/sre-internal/issues/2920#issue-2009797939

2024-05-08 15:52 UTC, t3chguy commented on .github/workflows/dockerhub.yaml
> +                    images+="${tag}@${DIGEST} "
```suggestion
                      images+="${tag}@${DIGEST} "
```

2024-05-08 15:52 UTC, t3chguy approved these changes
Looks sane otherwise

2024-05-13 10:49 UTC, merged