Remove very outdated loading-test.tsx
element-hq/element-web pull request #27588
Opened 2024-06-17 18:15 UTC by richvdh

This test suite attempted to fire up a complete Element Web instance inside a jest environment. I created it way back in 2016, before Cypress, Playwright, or react-testing-library existed, and everything it does is now much better tested by our playwright tests.

It's now getting in my way for fixing https://github.com/element-hq/element-web/issues/27560. It's time to put it out of its misery.

2024-06-17 19:01 UTC, t3chguy requested changes
I think some of these aren't covered by playwright, e.g. guest registration, please replace them rather than remove them.

2024-06-18 08:55 UTC, richvdh commented
I'll have a look, but may end up having to pursue option B of just disabling crypto when running in an environment that doesn't support `structuredClone`.

2024-06-20 11:17 UTC, richvdh commented on test/app-tests/loading-test.tsx
> -        });
Replaced by https://github.com/matrix-org/matrix-react-sdk/pull/12660

2024-06-20 11:18 UTC, t3chguy approved these changes

2024-06-20 11:56 UTC, merged