Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `useIsEncrypted`
element-hq/element-web pull request #28282
Opened 2024-10-23 17:19 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

Task https://github.com/element-hq/element-web/issues/26922

2024-11-12 16:49 UTC, t3chguy commented on src/hooks/useIsEncrypted.ts
>          [cli, room],
can we not use `useAsyncEffect`?

2024-11-12 16:51 UTC, t3chguy commented on src/hooks/useIsEncrypted.ts
> +        func();
What is the point of `func` here rather than just making the method anonymous?

2024-11-12 16:52 UTC, t3chguy requested changes

2024-11-12 16:52 UTC, t3chguy commented on src/hooks/useIsEncrypted.ts
> +                    setIsEncrypted(false);
if `encrypted` is true and the room didn't change but `isEncryptionEnabledInRoom` threw should we really be setting to false? This seems unexpected.

We probably also need to reset to `null` when room changes whilst `func` is calling the async function which could take multiple ticks

2024-11-12 16:52 UTC, t3chguy commented on src/hooks/useIsEncrypted.ts
> +// Hook to simplify watching whether a Matrix room is encrypted, returns undefined if room is undefined, return null when isRoomEncrypted is computed
Do we really need both `undefined` and `null`? I'd suggest `null` for `if room is undefined or the state is loading`

2024-11-12 16:55 UTC, t3chguy reviewed
Could probably be also done like this:

```
const encryptionStateEvent = useRoomState(...);
return useAsyncMemo(() => {...}, [room, encryptionStateEvent]);
```

2024-11-12 17:18 UTC, florianduros commented
> Could probably be also done like this:
> 
> ```
> const encryptionStateEvent = useRoomState(...);
> return useAsyncMemo(() => {...}, [room, encryptionStateEvent]);
> ```

Are you suggesting to get the encryption state event with `useRoomState(room, (roomState) => roomState.getStateEvents(EventType.RoomEncryption))`. Where it should have only one (event)

2024-11-12 17:23 UTC, t3chguy commented
> Where it should have only one (event)

Yes but it'll be the dependency for `useAsyncMemo` so it reacts to state event updates

2024-11-13 09:53 UTC, t3chguy approved these changes

2024-11-13 10:48 UTC, merged