Simplified Sliding Sync
element-hq/element-web pull request #28515
Opened 2024-11-21 14:28 UTC by dbkr

Replaces the sliding sync option in labs with Simplified Sliding Sync so it will support the impl in Synapse directly rather than via the sliding sync proxy.

Requires https://github.com/matrix-org/matrix-js-sdk/pull/4400
Ported from https://github.com/element-hq/matrix-react-sdk/pull/36

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

2025-02-20 09:39 UTC, t3chguy requested changes

2025-02-20 09:39 UTC, t3chguy commented on playwright/e2e/sliding-sync/sliding-sync.spec.ts
> -    test("should not show unread indicators", async ({ page, app, joinedBot: bot, testRoom }) => {
Can we invert this test rather than removing it?

2025-02-20 09:39 UTC, t3chguy commented on playwright/e2e/sliding-sync/sliding-sync.spec.ts
> -    test("should send unsubscribe_rooms for every room switch", async ({ page, app }) => {
This seems still desirable. MSC4186 Simplified Sliding Sync still uses `room_subscriptions` which this was also asserting

2025-02-20 09:39 UTC, t3chguy commented on src/MatrixClientPeg.ts
> +            throw new Error(
Probably wants to be a UserFriendlyError for translation support

2025-02-20 09:39 UTC, t3chguy commented on src/settings/controllers/SlidingSyncController.ts
> +    }
This seems moot

2025-02-20 09:39 UTC, t3chguy commented on src/components/structures/TimelinePanel.tsx
The changes here look unrelated

2025-03-10 13:56 UTC, dbkr commented on playwright/e2e/sliding-sync/sliding-sync.spec.ts
> -    test("should not show unread indicators", async ({ page, app, joinedBot: bot, testRoom }) => {
Sure... done.

2025-03-10 16:00 UTC, t3chguy approved these changes

2025-03-18 18:12 UTC, merged