Revert `GoToHome` keyboard shortcut to `Ctrl`–`Alt`–`H` on macOS
element-hq/element-web pull request #28577
Opened 2024-11-27 09:34 UTC by gy-mate

Fixes #28576 by partially reverting https://github.com/matrix-org/matrix-react-sdk/pull/7631/

## Checklist

-   [x] ~~Tests written for new code (and old code if feasible).~~ N/A
-   [x] ~~New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.~~ N/A
-   [] Linter and other CI checks pass.
-   [x] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

2024-12-24 14:53 UTC, florianduros commented
Hi,

The issue is specific to safari and the fix will remove the shortcut all the others browsers on Macos (firefox, chrome...).

2024-12-24 20:05 UTC, gy-mate commented
> the fix will remove the shortcut all the others browsers on Macos (firefox, chrome...)

@florianduros Why is that? I just wanted to _change_ the shortcut to `Ctrl`–`Alt`–`H`.

2025-02-10 09:17 UTC, florianduros requested changes
Hi sorry for the delay

2025-02-10 09:17 UTC, florianduros commented on src/accessibility/KeyboardShortcuts.ts
> +            ctrlKey: true,
This goes against the PR description, this is not `Ctrl–Alt–H`.

2025-02-10 09:31 UTC, gy-mate commented on src/accessibility/KeyboardShortcuts.ts
> +            ctrlKey: true,
My bad—I've corrected the title of the PR! I hope it's okay now.

2025-02-10 16:06 UTC, florianduros approved these changes
Tested and it works, thanks for the contribution

2025-02-10 16:29 UTC, merged