Add delay in test to allow Alice to fetch Bob's device keys
element-hq/element-web pull request #28668
Opened 2024-12-05 22:21 UTC by uhoreg

The latest Rust crypto crate requires the device keys of the device requesting verification before it accepts an incoming verification, and will drop the verification request if it doesn't have it.  This causes CI failures because the CI requests the verification too quickly, before the test user has a chance to get the bot's device keys.

Fixes a CI failure for https://github.com/matrix-org/matrix-js-sdk/pull/4566 (https://github.com/matrix-org/matrix-js-sdk/actions/runs/12158968697/job/33908198078)

## Checklist

- [ ] Tests written for new code (and old code if feasible).
- [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
- [ ] Linter and other CI checks pass.
- [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

2024-12-06 09:05 UTC, florianduros requested changes
If we can avoid timeout in e2e tests, it will be great

Can we instead?
1. spy the return of an http call
2. or assert something in the UI that is the resultant of device keys download

2024-12-06 19:56 UTC, uhoreg commented
Yeah, I wasn't too enthused about adding a delay, but I also wanted to make sure that the client was fetching the key automatically on its own, rather than in response to some UI action.  But I can change it.

2024-12-09 08:36 UTC, florianduros approved these changes

2024-12-09 08:36 UTC, florianduros commented on playwright/e2e/crypto/user-verification.spec.ts
> + */
```suggestion
/** 
 * Wait until we get the other user's device keys.
 * In newer rust-crypto versions, the verification request will be ignored if we
 * don't have the sender's device keys.
 */
```

2024-12-09 21:20 UTC, merged