Update docker nginx config to not force ipv6
element-hq/element-web pull request #28771
Opened 2024-12-19 03:40 UTC by yxie2023

Per PR #28729: CLA is signed and am now contributing from "contrib" branch.

2024-12-19 03:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/element-web?pullRequest=28771) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/element-web?pullRequest=28771) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yxie2023<br/>:x: x<br/><hr/>**x** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/element-web?pullRequest=28771) it.</sub>

2024-12-19 09:30 UTC, t3chguy requested changes
See above

2025-01-10 21:13 UTC, yxie2023 commented
Sorry. Not sure I understand 100%.

- "x" is my local unix account.
- not sure about the commit / rebase part.

Is it possible to abandon this PR and instead for you (or someone else) to commit this 1-line fix? Thank you!

2025-01-10 22:22 UTC, t3chguy commented
@yxie2023 https://github.com/element-hq/element-web/pull/28771/commits/8d3c1915f7706531da73d654a42f55d8e6924841 says it was committed by someone called `x`, not yourself.

> Is it possible to abandon this PR and instead for you (or someone else) to commit this 1-line fix? Thank you!

Not without a piece of paper to give me rights over the code, otherwise `x` could come and claim copyright over it, unfortunately

2025-03-21 08:53 UTC, t3chguy commented
Unfortunately this won't work anymore due to switching to using Nginx envsubst templates which are not parsed until after entrypoint 10-.

See upstream issue https://github.com/nginx/docker-nginx/issues/947

2025-03-21 08:53 UTC, closed without merging